<?php
/**
 * Conesa/ScheduleDelivery/view/adminhtml/templates/order/view/schedule_info.phtml
 *
 * @var \Conesa\ScheduleDelivery\Block\Adminhtml\Order\View\ScheduleInfo $block
 */
?>
<?php $order = $block->getOrder() ?>
<?php
// Usamos getData() para acceder a los atributos personalizados
$scheduleDeliveryDate = $order->getData('schedule_delivery_date');
$scheduleDeliveryTimeSlot = $order->getData('schedule_delivery_time_slot');
?>

<?php if ($scheduleDeliveryDate): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <strong class="title"><?= $block->escapeHtml(__('Información de Entrega Programada')) ?></strong>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Fecha de Entrega')) ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <?= $block->escapeHtml($scheduleDeliveryDate) ?>
                </div>
            </div>
            <div class="admin__page-section-item">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Rango Horario')) ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <?= $block->escapeHtml($scheduleDeliveryTimeSlot) ?>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>